# Generated by Django 4.1.1 on 2022-09-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    ]
