# Generated by Django 4.1.1 on 2022-09-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_descripton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descripton',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default='a', help_text='Please add unique value', max_length=20, unique=True, verbose_name='stock keeping unit'),
        ),
    ]
