# Generated by Django 4.1.1 on 2022-09-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderedproducts_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
